name: tiraz_mobile
description: Tiraz mobile app (Flutter) - boilerplate
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
